### ISSUE TITLE
Which python version should be used?

### ISSUE THREAD

**Issue by SimZhou** [phecda-xu/RIR-Generator#2]
in python 3.9.12
failed to install numpy in requirements. 
said:
```
  × Running setup.py install for numpy did not run successfully.
  │ exit code: 1
  ╰─> [146 lines of output]
      Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)


      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      blis_info:
      customize UnixCCompiler
        libraries blis not found in ['/mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      openblas_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
      Setting PTATLAS=ATLAS
      get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
      customize Gnu95FCompiler
      Found executable /usr/bin/gfortran
      customize Gnu95FCompiler
      customize Gnu95FCompiler using config
      compiling '_configtest.c':

      /* This file is generated from numpy/distutils/system_info.py */
      void ATL_buildinfo(void);
      int main(void) {
        ATL_buildinfo();
        return 0;
      }

      C compiler: gcc -pthread -B /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/include -I/mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/include -fPIC -O2 -isystem /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/include -fPIC

      compile options: '-c'
      gcc: _configtest.c
      gcc -pthread -B /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat _configtest.o -L/usr/lib64/atlas -ltatlas -o _configtest
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: warning: libgfortran.so.3, needed by /usr/lib64/atlas/libtatlas.so, not found (try using -rpath or -rpath-link)
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: warning: libm.so.6, needed by /usr/lib64/atlas/libtatlas.so, not found (try using -rpath or -rpath-link)
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_compare_string@GFORTRAN_1.0'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sqrtl@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sin@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sincosf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `lround@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sinf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_stop_string@GFORTRAN_1.0'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_st_write_done@GFORTRAN_1.0'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_pow_i4_i4@GFORTRAN_1.0'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `pow@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `log@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `atan2@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `log10@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `logf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `cosf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `log10f@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_st_write@GFORTRAN_1.0'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `cos@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `csqrt@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sqrt@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sqrtf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `sincos@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_transfer_integer_write@GFORTRAN_1.4'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `csqrtf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_transfer_character_write@GFORTRAN_1.4'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `powf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `atan2f@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `lroundf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `cabsf@GLIBC_2.2.5'
      /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat/ld: /usr/lib64/atlas/libtatlas.so: undefined reference to `cabs@GLIBC_2.2.5'
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o _configtest.o.d
      Status: 255
      Output: compiling '_configtest.c':

      /* This file is generated from numpy/distutils/system_info.py */
      void ATL_buildinfo(void);
      int main(void) {
        ATL_buildinfo();
        return 0;
      }

      C compiler: gcc -pthread -B /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/include -I/mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/include -fPIC -O2 -isystem /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/include -fPIC

      compile options: '-c'
      gcc: _configtest.c
      gcc -pthread -B /mnt/lustre02/jiangsu/aispeech/home/yhz25/.conda/envs/rir/compiler_compat _configtest.o -L/usr/lib64/atlas -ltatlas -o _configtest

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/setup.py", line 415, in <module>
          setup_package()
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/setup.py", line 407, in setup_package
          setup(**metadata)
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/setup.py", line 164, in configuration
          config.add_subpackage('numpy')
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/misc_util.py", line 1034, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/misc_util.py", line 1000, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/setup.py", line 10, in configuration
          config.add_subpackage('core')
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/misc_util.py", line 1034, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/misc_util.py", line 1000, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/core/setup.py", line 760, in configuration
          blas_info = get_info('blas_opt', 0)
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 446, in get_info
          return cl().get_info(notfound_action)
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 639, in get_info
          self.calc_info()
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 1641, in calc_info
          atlas_info = get_info('atlas_3_10_blas_threads')
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 446, in get_info
          return cl().get_info(notfound_action)
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 639, in get_info
          self.calc_info()
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 1294, in calc_info
          atlas_version, atlas_extra_info = get_atlas_version(**atlas)
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 1535, in get_atlas_version
          'ATLAS_INFO', _c_string_literal(atlas_version))
        File "/tmp/pip-install-ghumvfwj/numpy_0cd1dbbe8c124588a5f914de0d2d84d6/numpy/distutils/system_info.py", line 175, in _c_string_literal
          s = s.replace('\\', r'\\')
      AttributeError: 'NoneType' object has no attribute 'replace'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> numpy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.


```

**Comment by SimZhou** [comment]
Changed to python 3.7.13 and worked.
